# Site settings
title: El Manouche
email: me@elmanou.ch
description: > # ignore newlines
  Redirection to main website
# logo: /assets/img/logo.png

theme: jekyll-theme-minimal

gems:
  - jekyll-redirect-from
