# Site settings
title: Sarah Dionne
email: sarah@dionne.ch
description: > # ignore newlines
  Physiothérapie pédiatrique · Acupuncture · Reiki
# logo: /assets/img/logo.png

theme: jekyll-theme-minimal

gems:
  - jekyll-redirect-from
